# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

command_line:
  - sensor:
      name: "Rumstemperatur"
      command: "ssh pi@nipsu cat /sys/bus/w1/devices/28-0316a082c5ff/temperature"
      unit_of_measurement: "C"
      value_template: "{{ (value | int) / 1000 | round(1) }}"
  - switch:
      command_on: "ssh pi@nipsu tdtool --dimlevel 255 --dim kok1"
      command_off: "ssh pi@nipsu tdtool --dimlevel 0 --dim kok1"
      name: "Kök stora fönstret"
  - switch:
      command_on: "ssh pi@nipsu tdtool --on kok2"
      command_off: "ssh pi@nipsu tdtool --off kok2"
      name: "Kök lilla fönstret"
  - switch:
      command_on: "ssh pi@nipsu tdtool --on kok3"
      command_off: "ssh pi@nipsu tdtool --off kok3"
      name: "Kok lampa"
  - switch:		
      command_on: "ssh pi@nipsu tdtool --on sov1"
      command_off: "ssh pi@nipsu tdtool --off sov1"
      name: "Sovrum mot trädgård"
  - switch:
      command_on: "ssh pi@nipsu tdtool --on sov2"
      command_off: "ssh pi@nipsu tdtool --off sov2"
      name: "Sovrum mot Hermelinsgatan"
  - switch:
      command_on: "ssh pi@nipsu tdtool --on arb1"
      command_off: "ssh pi@nipsu tdtool --off arb1"
      name: "Arbetsrum fönster"
  - switch:	
      command_on: "ssh pi@nipsu tdtool --on arb2"
      command_off: "ssh pi@nipsu tdtool --off arb2"
      name: "Ivarhyllan"
  - switch:
      command_on: "ssh pi@nipsu tdtool --on sal1"
      command_off: "ssh pi@nipsu tdtool --off sal1"
      name: "Sal fönster mot Hermelinsgatan"
  - switch:
      command_on: "ssh pi@nipsu tdtool --on sal2"
      command_off: "ssh pi@nipsu tdtool --off sal2"
      name: "Sal fönster mot Föraregatan och hylla"

camera:
  - platform: ffmpeg
    name: nipsu
    input: rtsp://nipsu.lan:8554/unicast

